spring:
  datasource:
    url: jdbc:postgresql://postgres_db:5432/runner-serviceDB
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    platform: postgres

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update