auth0:
  audience: ${AUTH0_AUDIENCE}

spring:
  application:
    name: snippet-runner
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_SERVER_URI}
          client-id: ${AUTH_CLIENT_ID}
          client-secret: ${AUTH_CLIENT_SECRET}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

server:
  port: 8080
  # port: 8081

stream:
  lint.key: "lintRuleStream"
  format.key: "formatRuleStream"
  test.key: "testStream"
  runner.key: "runnerStream"

groups:
  lint: "lintGroup"
  format: "formatGroup"
  test: "testGroup"
  runner: "runnerGroup"

