# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle for Dev

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      # Si las dependencias privadas est√°n en GitHub Packages, podr√≠as necesitar 'packages: read' aqu√≠:
      # packages: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Configura Gradle para uso √≥ptimo en GitHub Actions, incluyendo el cach√©.
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      # Paso de Build: Inyecta las credenciales como variables de entorno (env)
      - name: Build with Gradle Wrapper and Credentials
        run: ./gradlew build
        env:
          GPR_USER: ${{ secrets.gpr.user }}
          GPR_KEY: ${{ secrets.gpr.key }}

  docker-publish:
    name: Build and Publish Docker Image
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        # Usamos GITHUB_TOKEN para loguearnos al GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Push Docker Image
        run: |
          IMAGE=ghcr.io/ingsis25/runner-service
          if [[ $GITHUB_REF == refs/heads/main ]]; then
            TAG=prod
          else
            TAG=dev
          fi
          echo "üöÄ Building image: $IMAGE:$TAG"
          docker build -t $IMAGE:$TAG .
          docker push $IMAGE:$TAG

      - name: Update service on VM with new image
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_KEY }}
          script: |
            pwd
            cd infra
            # Logueo con GITHUB_TOKEN para hacer 'docker pull' desde la VM
            echo ${{ secrets.GITHUB_TOKEN }} | sudo docker login -u ${{ github.actor }} --password-stdin ghcr.io
            sudo docker compose -f docker-compose.dev.yml pull runner-service
            sudo docker compose -f docker-compose.dev.yml up -d runner-service